version: '2'
services:
    teamcaring-app:
        image: teamcaring
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://teamcaring-mysql:3306/teamcaring?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=teamcaring-elasticsearch:9300
        ports:
            - 8080:8080
    teamcaring-mysql:
        extends:
            file: mysql.yml
            service: teamcaring-mysql
    teamcaring-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: teamcaring-elasticsearch
